# -*- coding: utf-8 -*-
"""Copia de Copia Taller_1 de ViveLabPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l0V3XW1HKdjxt2jGSj35HtZTABZ_CqeO
"""

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
texto="Hola Mundo Cruel.... Aqui estoy en el Kinder de Python"
print(texto)

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
print ("Hola Mundoooo...")

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
a=10
b=5
suma=a+b
print (suma)

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
print("EXPERIMENTO PERSONAL de Carlos Javier .....Menu......")
print("====================================\n")
print("1- Area del cuadrado")
print("2- Area de la Circunferencia")

op = input("Ingrese la opcion: ")

match op:
  case "1": 
    lado=float(input("Ingrese el valor del lado: "))
    Area= lado*lado
    print(f"El Area del Cuadrado es :{Area}")
  case "2":
    radio=float(input("Ingrese el valor del radio: "))
    area=((radio*radio)*(3.1416))
    print(f"El Area de la Circunferencia es :{area}")
  case _:
    print("sale")

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
mensaje1= "hola queridos Estudiantes"
encontrar=mensaje1.find("Estudiantes")
print(encontrar)

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
print("Programa que toma sus datos personales")
print("======================================")
nombre=input("Por favor ingrese su nombre completo: ")
movil=input("Por favor ingrese su numero de movil: ")
direccion=input("Por favor ingrese su direccion de Residencia: ")
estatura= float(input("Por favor ingrese su estatura en metros: "))
edad=int(input("Por favor ingrese su edad: "))

print(f"Muchas Gracias por sus datos {nombre} Hasta Pronto ...")

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
print("=====================================")
print("  Programa que suma dos numeros      ")
print("=====================================\n")
a=int(input("Por favor ingrese un numero: "))
b=int(input("Por favor ingrese un numero: "))
suma=a+b
suma=str(suma)
print(f" La Sumatoria es igual a: {suma}")

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
print("=======================================")
print("          Area Triangulo               ")
print("=====================================\n")

nombre=input("Por favor ingrese su nombre: ")
base=float(input("Por favor ingrese el Vr de la Base: "))
altura=float(input("Por favor ingresa el Vr de la Altura: "))
area=(base*altura)/2
str(area)
print(f"{nombre} El Area del Triangulo es ...  {round(area,2)}")

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
print("=======================================")
print("          Area del Circulo             ")
print("=====================================\n")

nombre=input("Por favor ingrese su nombre: ")
radio=float(input("Por favor ingrese el Vr del Radio: "))

areacirculo= 3.1416*(radio*radio)
str(areacirculo)
print(f"{nombre} El Area del Circulo es ...  {round(areacirculo,2)}")

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
print("===================================================================")
print(" Ejercicio de Condicionales IF-ELSE Programa que indica El Clima   ")
print("=================================================================\n")

nombreCiudad=input("Por favor ingrese nombre de La Ciudad : ")
temperatura=float(input("Por favor ingrese los Grados Celsius de Temperatura : "))

if temperatura <=20:
  print(f"El Clima de La Ciudad {nombreCiudad} es FRIOOOO... ")
else:
  print(f"El Clima de La Ciudad {nombreCiudad} es Templado...")

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
print("=======================================================================")
print(" Ejercicio de Condicionales ELIF- ELSE  Programa que indica El Clima   ")
print("=====================================================================\n")

nombreCiudad=input("Por favor ingrese nombre de La Ciudad : ")
temperatura=float(input("Por favor ingrese los Grados Celsius de Temperatura : "))

if temperatura <=20:
  print(f"El Clima de La Ciudad {nombreCiudad} es FRIOOOO... ")
elif temperatura >=20 and temperatura <=27:
  print(f"El Clima de La Ciudad {nombreCiudad} es Templado...")
elif temperatura >=30:
  print(f"El Clima de La Ciudad {nombreCiudad} es Caliente...")
else:
  print("Esos es Todo en cuanto al Clima")

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
print("=======================================================================")
print("       Ejercicio de Condicionales PARA PRESENTAR UN MENU               ")
print("=======================================================================\n")
print("1- Suma ")
print("2- Resta ")
print("3- Multiplicacion ")
print("4- Division ")
print("0- Salir del Programa ")
print()
op=int(input("Por favor ingrese la Opcion: "))
print()
if op==1:
  print("Ha elejido la Opcion para realizar una Suma de dos Numeros")
  a=float(input("Por fvor ingrese un Numero : "))
  b=float(input("Por fvor ingrese un Numero : "))
  sumatoria = a+b
  print(f"La Sumatoria es igual a {sumatoria}")

elif op==2:
  print("Ha elejido la Opcion para realizar una Resta de dos Numeros")
  a=float(input("Por fvor ingrese un Numero : "))
  b=float(input("Por fvor ingrese un Numero : "))
  sustraccion = a-b
  print(f"La Sustraccion es igual a {sustraccion}")
elif op==3:
  print("Ha elejido la Opcion para realizar una Multiplicacion de dos Numeros")
  a=float(input("Por fvor ingrese un Numero : "))
  b=float(input("Por fvor ingrese un Numero : "))
  producto = a*b
  print(f"El Producto  es igual a {producto}")
elif op==4:
  print("Ha elejido la Opcion para realizar una Division de dos Numeros")
  a=float(input("Por fvor ingrese un Numero : "))
  b=float(input("Por fvor ingrese un Numero : "))
  cociente = a/b
  print(f"El Cociente  es igual a {cociente}")
elif op==0:
  print("Gracias por usar este Programita...")
  exit

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
print("=======================================================================")
print("       Bienvenido al Sistema Calculo de Vacaciones la Tumbadora Fija   ")
print("=======================================================================\n")
nombre=input("Ingrese el Nombre del Empleado: ")
años=int(input("Ingrese Antiguedad en años: "))
print("=========================================================================")
print("1- Atencion al Cliente ")
print("2- Logistica ")
print("3- Gerencia ")
print("0- Salir del Programa ")
print()
op=int(input("Ingrese El Codigo del Departamento: "))
if op==1:
  if años==1:
    diasVacAtencionCliente=6
    print(f"Atencion al Cliente; Antiguedad {años }Años, sus Vacaciones son: {diasVacAtencionCliente} dias")
  else:
    print("El numero de Años para esta opcion debe ser de UNO...")
elif op==2:
    if años>=2 and años <=6:
      diasVacLogistica=14
      print(f"Logistica; Antiguedad {años } Años, sus Vacaciones son: {diasVacLogistica} dias")
    else:
      print("El numero de Años para esta opcion debe ser entre 2 y 6 años...")
elif op==3:
    if años>=7:
      diasVacGerencia=20
      print(f"Gerencia; Antiguedad {años } Años, sus Vacaciones son: {diasVacGerencia} dias")
    else:
      print("El numero de Años para esta opcion debe ser de 20 años...")
elif op==4:
  print("Gracias por usar este Programita... Bye")
  exit

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
print("=======================================================================")
print("       Ejercicio de PROMEDIO DE ESTUDIANTE VIVELAB-SENA                ")
print("=======================================================================\n")
nombreEstudiante= input("Por favor ingrese El Nombre del Estudiante: ")
print(" Notas del Estudiante ")
matematicas=float(input("Por favor ingrese la Nota de Matematicas: "))
ciencias=float(input("Por favor ingrese la Nota de Ciencias...: "))
geografia=float(input("Por favor ingrese la Nota de Geografia..: "))
informatica=float(input("Por favor ingrese la Nota de Informatica: "))
print()
promedio=(matematicas+ciencias+geografia+informatica)/4
if promedio >= 3.5:
    print(f"Su promedio {nombreEstudiante} es de {round(promedio,2)} Felicitaciones..!!! :-) APROBÓ el Curso")
else:
    print(f"Su promedio {nombreEstudiante} es de {round(promedio,2)} Lamentablemente :-( NO aprobó el Curso")
    print()
print("Gracias por usar este Programita ")
print()
exit

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
print("=======================================================================")
print("       Ejercicio de Condicionales COMPARACION ENTRE NUMEROS            ")
print("=======================================================================\n")
print()
nombre=input("Por favor ingrese su Nombre: ")
print()
num1=float(input("Por favor ingrese El Primer  Numero: "))
num2=float(input("Por favor ingrese El Segundo Numero: "))
print()
if num1==num2:
  print(f"Los numeros {num1} y {num2} SON IGUALES")
elif num1>num2:
  print(f"El Numero {num1} es MAYOR que el Numero {num2}")
elif num1<num2:
  print(f"El Numero {num1} es MENOR que el Numero {num2}")
else:
  print()
  print("Gracias por usar este Programita...Bye")
exit

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
print("=======================================================================")
print("       Ejercicio de Condicionales SIMULACION FACTURA                   ")
print("=======================================================================\n")
print()
nombre=input("Por favor ingrese su Nombre: ")
print()
articulo=input("Por favor ingrese nombre del Articulo: ")
cantidad=int(input("Por favor ingrese la Cantidad: "))
vrUnitario=float(input("Por favor ingrese Vr Unitario: "))
cobraIva=input("Por favor indique  si aplica IVA(19%) Escriba 's', no aplica escriba'n': ")
paga=float(input("Por favor ingrese Vlr pagado por Caja : "))
iva=0.19
if cantidad >0:
  subtotal=(cantidad*vrUnitario)
  print(f"El SubTotal es ${subtotal}")
else:
  print("Cantidad de Articulos debe ser mayor a Cero... ")
if cobraIva=="s":
  total=(subtotal*iva)+subtotal
  vriva=(subtotal*iva)
  cambio=paga-total
  if paga<total:
    print(f"Por favor revisar El pago pues faltan ${cambio}")
    paga=float(input("Por favor ingrese Vlr a pagar por Caja : "))
    cambio=paga-total
    print(f"vr. IVA (19%) ${vriva}; Total a Pagar ${total} pago recibido por caja ${paga} cambio a favor del cliente ${cambio}  ")
  
else:
  total=subtotal
  cambio=paga-subtotal
  if paga<total:
    print(f"Por favor revisar El pago pues faltan ${cambio}")
    paga=float(input("Por favor ingrese Vlr a pagar por Caja : "))
    cambio=paga-total
  print(f"Total apagar SIN IVA ${total} pago recibido por caja ${paga} cambio a favor del cliente ${cambio}  ")
print()
print("Gracias por utilizar este Programita... Bye")
exit

print("Carlos Javier De La Torre R. ...Taller Python ViveLab SENA... ")
print("==========================================================================================")
print("Ejercicio de Condicionales PARA PRESENTAR UN MENU CONVERTIR NUMEROS A LETRAS Y VISCEVERSA ")
print("========================================================================================\n")
print("1- Convertir Numeros a Letras ")
print("2- Convertir Letras a Numeros ")
print("0- Salir del Programa ")
print()
op=int(input("Por favor ingrese la Opcion: "))
print()
if op==1:
  print("Ha elejido la Opcion para Convertir de Numeros a Letras ")
  a=int(input("Por fvor ingrese un Numero : "))
  if a<1 and a>5:
    print("Por favor ingresar Numero en rango entre 1 hasta 5... ")
  elif a==1:
    num1=" UNO "
    print(f"El numero que ingreso es {a} y en letras es :  {num1}")
  elif a==2:
    num2=" DOS "
    print(f"El numero que ingreso es {a} y en letras es :  {num2}")
  elif a==3:
    num3=" TRES "
    print(f"El numero que ingreso es {a} y en letras es :  {num3}")
  elif a==4:
    num4=" CUATRO "
    print(f"El numero que ingreso es {a} y en letras es :  {num4}")
  elif a==5:
    num5=" CINCO "
    print(f"El numero que ingreso es {a} y en letras es :  {num5}")
    
if op==2:
  print("Ha elejido la Opcion para Convertir de Letras a NUMEROS ")
  b=input("Por fvor ingrese en letras el numero en rango de uno a cinco : ")
  if b<"uno" and b>"cinco":
    print("Por favor ingresar Numero en rango entre 1 hasta 5... ")
  elif b=="uno":
    num1=1
    print(f"El numero que ingreso en letras es {b} y en Numeros es :  {num1}")
  elif b=="dos":
    num2=2
    print(f"El numero que ingreso en letras es {b} y en Numeros es :  {num2}")
  elif b=="tres":
    num3=3
    print(f"El numero que ingreso en letras es {b} y en Numeros es :  {num3}")
  elif b=="cuatro":
    num4=4
    print(f"El numero que ingreso en letras es {b} y en Numero  es :  {num4}")
  elif b=="cinco":
    num5=5
    print(f"El numero que ingreso en letras es {b} y en Numero es :  {num5}")
  
elif op==0:
  print("Gracias por usar este Programita...")
  exit